### ISSUE TITLE
attempted to import the Node standard library module "node:stream"

### ISSUE THREAD

**Issue by linonetwo** [uhop/stream-chain#26]
The package at "node_modules\stream-chain\src\index.js" attempted to import the Node standard library module "node:stream".
It failed because the native React runtime does not include the Node standard library.

When upgrade from "stream-chain": "^2.2.5", to "stream-chain": "^3.3.2",

**Comment by uhop** [comment]
I don’t see how it can be fixed if some environment does not support the Node standard library. The best is to open a ticket with them and postpone the upgrading from 2.x to 3.x for now.

**Comment by linonetwo** [comment]
Yes, as 2.x is still useful and working, not upgrading it in restricted environment is OK.

**Comment by uhop** [comment]
I still suggest to open a ticket with React Native to support imports from the standard Node library. Deno, Bun and Node do that.
