### ISSUE TITLE
can not chain Node.ReadableStream

### ISSUE THREAD

**Issue by guoh27** [uhop/stream-chain#9]
I can not write this code in my ts file:
```typescript
const stream: Node.ReadableStream = ...
chain([stream, ...])
```
There will has type error

**Comment by guoh27** [comment]
And
```js
const stream: Node.ReadableStream = ...
const pipeline = chain([...])
stream.pipe(pipeline)
pipeline.on('end', () => {
    console.log('end')
}
```
pipeline will not end after stream is ended

**Comment by uhop** [comment]
`stream-chain` does not support `ReadableStream`. It is a part of web streams: https://nodejs.org/api/webstreams.html

`stream-chain` was written for Node streams: https://nodejs.org/api/stream.html

Web Streams were added in Node 16 and are still considered experimental. I plan to add them later when they stabilize.

**Comment by adamhamlin** [comment]
> `stream-chain` does not support `ReadableStream`. It is a part of web streams: https://nodejs.org/api/webstreams.html
> 
> `stream-chain` was written for Node streams: https://nodejs.org/api/stream.html
> 
> Web Streams were added in Node 16 and are still considered experimental. I plan to add them later when they stabilize.

@uhop great library! Just wanted to comment that I'm looking forward to WebStream support in the future 👍
